[package]
org= "ballerinax"
name= "cosmosdb"
version= "0.1.0"
authors = ["Ballerina"]
keywords = ["azure", "cosmosdb"]
repository = "https://github.com/ballerina-platform/module-ballerinax-azure-cosmosdb"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded=true

[dependencies]

