[package]
distribution = "2201.8.0"
org= "ballerinax"
name= "azure_cosmosdb"
version = "4.2.0"
authors = ["Ballerina"]
keywords = ["IT Operations/Databases", "Cost/Paid", "Vendor/Microsoft"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-azure-cosmosdb"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded=true

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerinax"
artifactId = "cosmosdb"
version = "4.2.0"
path = "../native/build/libs/azure-cosmosdb-native-4.2.0.jar"

[[platform.java17.dependency]]
groupId = "com.azure"
artifactId = "azure-cosmos"
version = "4.52.0"
path = "./lib/azure-cosmos-4.52.0.jar"

[[platform.java17.dependency]]
groupId = "io.netty"
artifactId = "netty-resolver-dns"
version = "4.1.100.Final"
path = "./lib/netty-resolver-dns-4.1.100.Final.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-handler"
version = "4.1.100.Final"
path = "./lib/netty-handler-4.1.100.Final.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-transport-native-unix-common"
version = "4.1.100.Final"
path = "./lib/netty-transport-native-unix-common-4.1.100.Final.jar"

[[platform.java11.dependency]]
groupId = "io.projectreactor.netty"
artifactId = "reactor-netty-core"
version = "1.1.13"
path = "./lib/reactor-netty-core-1.1.13.jar"

[[platform.java11.dependency]]
groupId = "io.projectreactor.netty"
artifactId = "reactor-netty"
version = "1.1.13"
path = "./lib/reactor-netty-1.1.13.jar"

[[platform.java11.dependency]]
groupId = "io.projectreactor.netty"
artifactId = "reactor-netty-http"
version = "1.1.13"
path = "./lib/reactor-netty-http-1.1.13.jar"

[[platform.java11.dependency]]
groupId = "io.micrometer"
artifactId = "micrometer-observation"
version = "1.12.0"
path = "./lib/micrometer-observation-1.12.0.jar"

[[platform.java11.dependency]]
groupId = "io.micrometer"
artifactId = "micrometer-core"
version = "1.12.0"
path = "./lib/micrometer-core-1.12.0.jar"

[[platform.java11.dependency]]
groupId = "io.micrometer"
artifactId = "micrometer-commons"
version = "1.12.0"
path = "./lib/micrometer-commons-1.12.0.jar"

