[package]
org= "ballerinax"
name= "azure_cosmosdb"
version= "0.1.6-SNAPSHOT"
authors = ["Ballerina"]
keywords = ["dev tools/databases", "cost/paid", "vendor/microsoft"]
repository = "https://github.com/ballerina-platform/module-ballerinax-azure-cosmosdb"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded=true
