[package]
distribution = "2201.0.1"
org= "ballerinax"
name= "azure_cosmosdb"
version= "3.0.0"
authors = ["Ballerina"]
keywords = ["IT Operations/Databases", "Cost/Paid", "Vendor/Microsoft"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-azure-cosmosdb"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded=true

[[platform.java11.dependency]]
path = "../cosmos-native/build/libs/cosmos-native-3.0.0-all.jar"
groupId = "io.ballerinax"
artifactId = "cosmosdb"
version = "3.0.0"
