[project]
org-name= "ballerinax"
version= "0.1.0"

[build-options]
observability-included=true

[dependencies]

[platform]
target = "java8"

    [[platform.libraries]]
    path = "./src/azure_cosmosdb/javautils/TokenGenerate-1.0-SNAPSHOT.jar"
    modules = ["azure_cosmosdb"]
