name: CI

on:
  push:
    branches-ignore:
      - "automated/dependency_version_update"
      - "automated/dependency_version_update_tmp"
  repository_dispatch:
    types:
      check_connector_for_breaking_changes

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                  java-version: 11
            - name: Grant execute permission for gradlew
              run: chmod +x gradlew
            - name: Build with Gradle
              env:
                  packageUser: ${{ github.actor }}
                  packagePAT: ${{ secrets.GITHUB_TOKEN }}
                  JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true
              run: |
                  ./gradlew build
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@nightly
              with:
                  args:
                      pack ./cosmosdb
              env:
                JAVA_HOME: /usr/lib/jvm/default-jvm
            - name: Ballerina Test
              uses: ballerina-platform/ballerina-action/@nightly
              with:
                  args:
                      test --test-report --code-coverage --coverage-format=xml ./cosmosdb
              env:
                  BASE_URL: ${{ secrets.BASE_URL }}
                  MASTER_OR_RESOURCE_TOKEN: ${{ secrets.MASTER_OR_RESOURCE_TOKEN }} 
                  JAVA_HOME: /usr/lib/jvm/default-jvm

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v3
            
            - name: Alert notifier on failure
              if: failure() && (github.event.action == 'check_connector_for_breaking_changes')
              run: |
                curl -X POST \
                'https://api.github.com/repos/ballerina-platform/ballerina-release/dispatches' \
                --header 'Accept: application/vnd.github.v3+json' \
                --header 'Authorization: Bearer ${{ secrets.BALLERINA_BOT_TOKEN }}' \
                --data-raw '{
                  "event_type": "notify-ballerinax-connector-build-failure",
                  "client_payload": {
                    "repoName": "module-ballerinax-azure-cosmosdb",
                    "workflow": "CI"
                  }
                }'
